[package]
name = "example-rust-divan"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "2.0" }

[[bench]]
name = "benchmarks"
harness = false